version: '3.9'

services:
  website:
    image: 'ghcr.io/discordlookup/discordlookup:main'
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: pause
        order: start-first
    environment:
      APP_NAME: DiscordLookup
      APP_ENV: production
      APP_KEY: ''
      APP_DEBUG: 'false'
      APP_URL: https://discordlookup.com
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: dragonfly
      REDIS_PORT: 6379
      REDIS_PASSWORD: dragonfly
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      SENTRY_LARAVEL_DSN: ''
      SENTRY_TRACES_SAMPLE_RATE: 1.0
      DISCORD_CLIENT_ID: 892399371910524938
      DISCORD_CLIENT_SECRET: ''
      DISCORD_BOT_TOKEN: ''
      DISCORD_REDIRECT_URI: https://discordlookup.com/auth/callback
      DISCORD_GUILD_ID: 980791496833908778
      DISCORD_INVITE_URL: https://discord.com/oauth2/authorize?client_id=892399371910524938&permissions=275951963136&scope=bot%20applications.commands
      DISCORD_EXPERIMENTS_WORKER: https://experiments.workers.discordlookup.com
      PLAUSIBLE_URL: ''
      PLAUSIBLE_WEBSITE_DOMAIN: 'discordlookup.com'
      LEGAL_FIRSTNAME: ''
      LEGAL_LASTNAME: ''
      LEGAL_ADDRESS: ''
      LEGAL_ADDRESS_ADDITIONAL: ''
      LEGAL_ZIPCODE: ''
      LEGAL_CITY: ''
      LEGAL_COUNTRY: ''
      LEGAL_PHONE: ''
      LEGAL_EMAIL: ''
    ports:
      - 8080:8080
    networks:
      - discordlookup
    depends_on:
      - postgres
      - dragonfly
  postgres:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    networks:
      - discordlookup
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  dragonfly:
    image: ghcr.io/dragonflydb/dragonfly:v1.25.4
    restart: unless-stopped
    ulimits:
      memlock: -1
    environment:
      DFLY_requirepass: dragonfly
    volumes:
      - dragonfly:/data
    networks:
      - discordlookup

volumes:
  postgres:
  dragonfly:

networks:
  discordlookup:
