version: '3.3'

services:
    website:
        image: 'ghcr.io/discordlookup/discordlookup:main'
        restart: unless-stopped
        env_file: .env.example
        depends_on:
            - mysql
        ports:
            - 127.0.0.1:8080:80
        networks:
            - discordlookup
        labels:
            - 'com.centurylinklabs.watchtower.scope=discordlookup-website'
    mysql:
        image: mariadb:10.11
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=discordlookup
            - MYSQL_DATABASE=discordlookup
            - MYSQL_USER=discordlookup
            - MYSQL_PASSWORD=discordlookup
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - discordlookup
        labels:
            - 'com.centurylinklabs.watchtower.scope=discordlookup-website'
    redis:
        image: redis:7.2
        restart: unless-stopped
        volumes:
            - redis:/data
        networks:
            - discordlookup
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 3s
            timeout: 3s
            retries: 5
        labels:
            - 'com.centurylinklabs.watchtower.scope=discordlookup-website'
    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --interval 120 --cleanup --scope discordlookup-website
        labels:
            - 'com.centurylinklabs.watchtower.scope=discordlookup-website'

volumes:
    mysql:
    redis:

networks:
    discordlookup:
        driver: bridge
